// game resources
var g_resources = [{
  name: "inside_tileset",
  type: "image",
  src: "data/images/inside_tileset.png"
}, {
  name: "outside_tileset",
  type: "image",
  src: "data/images/outside_tileset.png"
}, {
  name: "outside_01",
  type: "tmx",
  src: "data/outside_01.tmx"
}, {
  name: "outside_02",
  type: "tmx",
  src: "data/outside_02.tmx"
}, {
  name: "outside_03",
  type: "tmx",
  src: "data/outside_03.tmx"
}, {
  name: "outside_04",
  type: "tmx",
  src: "data/outside_04.tmx"
}, {
  name: "outside_05",
  type: "tmx",
  src: "data/outside_05.tmx"
}, {
  name: "outside_06",
  type: "tmx",
  src: "data/outside_06.tmx"
}, {
  name: "outside_caz_portal",
  type: "tmx",
  src: "data/outside_caz_portal.tmx"
}, {
  name: "outside_caz_portal_checkpoint",
  type: "tmx",
  src: "data/outside_caz_portal_checkpoint.tmx"
}, {
  name: "caz_room",
  type: "tmx",
  src: "data/caz_room.tmx"
}, {
  name: "inside_start",
  type: "tmx",
  src: "data/inside_start.tmx"
}, {
  name: "inside_01",
  type: "tmx",
  src: "data/inside_01.tmx"
}, {
  name: "inside_02",
  type: "tmx",
  src: "data/inside_02.tmx"
}, {
  name: "inside_03",
  type: "tmx",
  src: "data/inside_03.tmx"
}, {
  name: "inside_04",
  type: "tmx",
  src: "data/inside_04.tmx"
}, {
  name: "inside_05",
  type: "tmx",
  src: "data/inside_05.tmx"
}, {
  name: "inside_start_checkpoint",
  type: "tmx",
  src: "data/inside_start_checkpoint.tmx"
}, {
  name: "inside_goose_portal",
  type: "tmx",
  src: "data/inside_goose_portal.tmx"
}, {
  name: "inside_goose_portal_checkpoint",
  type: "tmx",
  src: "data/inside_goose_portal_checkpoint.tmx"
}, {
  name: "goose_room",
  type: "tmx",
  src: "data/goose_room.tmx"
}, {
  name: "adam_animate",
  type: "image",
  src: "data/images/adam_animate.png"
}, {
  name: "game_over",
  type: "image",
  src: "data/images/game_over.png"
}, {
  name: "story_screen",
  type: "image",
  src: "data/images/story_screen.png"
}, {
  name: "dialog_box",
  type: "image",
  src: "data/images/dialog_box.png"
}, {
  name: "bullet",
  type: "image",
  src: "data/images/bullet.png"
}, {
  name: "one_up",
  type: "image",
  src: "data/images/one_up.png"
}, {
  name: "health_bar",
  type: "image",
  src: "data/images/health_bar.png"
}, {
  name: "one_health",
  type: "image",
  src: "data/images/one_health.png"
}, {
  name: "one_goose_health",
  type: "image",
  src: "data/images/one_goose_health.png"
}, {
  name: "small_health",
  type: "image",
  src: "data/images/small_health.png"
}, {
  name: "large_health",
  type: "image",
  src: "data/images/large_health.png"
}, {
  name: "cazbot",
  type: "image",
  src: "data/images/cazbot.png"
}, {
  name: "robo_car",
  type: "image",
  src: "data/images/robo_car.png"
}, {
  name: "enemy_die",
  type: "image",
  src: "data/images/enemy_die.png"
}, {
  name: "platform",
  type: "image",
  src: "data/images/platform.png"
}, {
  name: "gooseman",
  type: "image",
  src: "data/images/gooseman.png"
}, {
  name: "hit",
  type: "image",
  src: "data/images/hit.png"
}, {
  name: "splash",
  type: "image",
  src: "data/images/splash.png"
}, {
  name: "other_bullet",
  type: "image",
  src: "data/images/other_bullet.png"
}, {
  name: "shield_bot",
  type: "image",
  src: "data/images/shield_bot.png"
}, {
  name: "sweeper",
  type: "image",
  src: "data/images/sweeper.png"
}, {
  name: "vanishing_platform",
  type: "image",
  src: "data/images/vanishing_platform.png"
}, {
  name: "spring",
  type: "image",
  src: "data/images/spring.png"
}, {
  name: "robot_bat",
  type: "image",
  src: "data/images/robot_bat.png"
}, {
  name: "mech_bot",
  type: "image",
  src: "data/images/mech_bot.png"
}, {
  name: "spinning_bot",
  type: "image",
  src: "data/images/spinning_bot.png"
}, {
  name: "wall_turret",
  type: "image",
  src: "data/images/wall_turret.png"
}, {
  name: "selector",
  type: "image",
  src: "data/images/selector.png"
}, {
  name: "fontx8",
  type: "image",
  src: "data/images/fontx8.png"
}, {
  name: "zap-it-title",
  type: "image",
  src: "data/images/zap-it-title.png"
}, {
  name: "f-bomb",
  type: "image",
  src: "data/images/f-bomb.png"
}, {
  name: "fbomb-explosion",
  type: "image",
  src: "data/images/fbomb-explosion.png"
}, {
  name: "boss_music",
  type: "audio",
  src: "data/music/",
  channel: 1
}, {
  name: "inside_music",
  type: "audio",
  src: "data/music/",
  channel: 1
}, {
  name: "title_music",
  type: "audio",
  src: "data/music/",
  channel: 1
}, {
  name: "game_over",
  type: "audio",
  src: "data/music/",
  channel: 1
}, {
  name: "beat_boss",
  type: "audio",
  src: "data/music/",
  channel: 1
}, {
  name: "outside_music",
  type: "audio",
  src: "data/music/",
  channel: 1
}, {
  name: "death",
  type: "audio",
  src: "data/sfx/",
  channel: 1
}, {
  name: "hit",
  type: "audio",
  src: "data/sfx/",
  channel: 1
}, {
  name: "fbomb",
  type: "audio",
  src: "data/sfx/",
  channel: 2
}, {
  name: "shoot",
  type: "audio",
  src: "data/sfx/",
  channel: 2
}, {
  name: "deflect",
  type: "audio",
  src: "data/sfx/",
  channel: 2
}, {
  name: "one_health",
  type: "audio",
  src: "data/sfx/",
  channel: 2
}, {
  name: "enemy_explosion",
  type: "audio",
  src: "data/sfx/",
  channel: 1
}, {
  name: "enemy_hit",
  type: "audio",
  src: "data/sfx/",
  channel: 1
}, {
  name: "life",
  type: "audio",
  src: "data/sfx/",
  channel: 1
}, {
  name: "enemy_shoot",
  type: "audio",
  src: "data/sfx/",
  channel: 1
}, {
  name: "splash",
  type: "audio",
  src: "data/sfx/",
  channel: 1
}, {
  name: "platform",
  type: "audio",
  src: "data/sfx/",
  channel: 1
}, {
  name: "spring",
  type: "audio",
  src: "data/sfx/",
  channel: 1
}, {
  name: "teleport",
  type: "audio",
  src: "data/sfx/",
  channel: 1
}, {
  name: "landing",
  type: "audio",
  src: "data/sfx/",
  channel: 1
}];
